---
  - name: Install core NvIPAM components
    yum: name={{item}} state=present update_cache=yes
    with_items:
      - libselinux-python
      - libsemanage-python
      - git
      - python36
      - python36-pip
      - gcc
      - gcc-c++
      - make
      - python36-devel
